server {
    listen $PORT;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    default_type application/octet-stream;

    location ~* \.(js|mjs)$ {
        add_header Content-Type application/javascript;
        try_files $uri =404;
    }

    location ~* \.css$ {
        add_header Content-Type text/css;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}